// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// osd_tx //
// ------ //

#define osd_tx_wrap_target 0
#define osd_tx_wrap 28
#define osd_tx_pio_version 0

static const uint16_t osd_tx_program_instructions[] = {
            //     .wrap_target
    0xc000, //  0: irq    nowait 0
    0xe000, //  1: set    pins, 0
    0x20a0, //  2: wait   1 pin, 0
    0x2020, //  3: wait   0 pin, 0
    0xec56, //  4: set    y, 22                  [12]
    0x1f85, //  5: jmp    y--, 5                 [31]
    0x00c2, //  6: jmp    pin, 2
    0x20a0, //  7: wait   1 pin, 0
    0xe03f, //  8: set    x, 31
    0xe04f, //  9: set    y, 15
    0x2920, // 10: wait   0 pin, 0               [9]
    0x0e8b, // 11: jmp    y--, 11                [14]
    0x00c9, // 12: jmp    pin, 9
    0xe058, // 13: set    y, 24
    0x1a8e, // 14: jmp    y--, 14                [26]
    0x00d1, // 15: jmp    pin, 17
    0x0009, // 16: jmp    9
    0x0049, // 17: jmp    x--, 9
    0xe02a, // 18: set    x, 10
    0x2020, // 19: wait   0 pin, 0
    0xf95d, // 20: set    y, 29                  [25]
    0x1d95, // 21: jmp    y--, 21                [29]
    0x00d8, // 22: jmp    pin, 24
    0x0000, // 23: jmp    0
    0xe05f, // 24: set    y, 31
    0xe003, // 25: set    pins, 3
    0x0899, // 26: jmp    y--, 25                [8]
    0xe000, // 27: set    pins, 0
    0x0053, // 28: jmp    x--, 19
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program osd_tx_program = {
    .instructions = osd_tx_program_instructions,
    .length = 29,
    .origin = -1,
    .pio_version = osd_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config osd_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + osd_tx_wrap_target, offset + osd_tx_wrap);
    return c;
}
#endif

