// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// osd_tx //
// ------ //

#define osd_tx_wrap_target 0
#define osd_tx_wrap 0
#define osd_tx_pio_version 0

static const uint16_t osd_tx_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program osd_tx_program = {
    .instructions = osd_tx_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = osd_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config osd_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + osd_tx_wrap_target, offset + osd_tx_wrap);
    return c;
}
#endif

